### ISSUE TITLE
use ade20k dataset

### ISSUE THREAD

**Issue by Robert-Hopkins** [saic-vul/ritm_interactive_segmentation#11]
Thanks for your job. I'm trying to train a model with ade20k, but I can't find the “annotations-object-segmentation.pkl” in the ade20k.py, line 69. Can you offer me this pkl file? thank you

**Comment by tomo0530** [comment]
Hi all, Thank you so much for this great app.
I have the same issue mentioned above. Could you send me the pickle file as well?

**Comment by franchesoni** [comment]
same
