### ISSUE TITLE
Training time 

### ISSUE THREAD

**Issue by UndecidedBoy** [saic-vul/ritm_interactive_segmentation#3]
Hello,

Great work and GitHub repository! 
I'm curious about the duration needed to complete training, was it a matter of days or weeks (for the Nvidia Tesla P40 GPUs you used)? 

Best!

**Comment by ksofiyuk** [comment]
It takes about 2-3 day to train the HRNet18 IT-M model on COCO+LVIS using two Tesla P40.

**Comment by UndecidedBoy** [comment]
Thanks for the response.
