### ISSUE TITLE
Resolution of image

### ISSUE THREAD

**Issue by iresusharma** [saic-vul/ritm_interactive_segmentation#8]
Hi! Thanks for sharing amazing work. I have noticed that while using pre-trained model, it is not working as fine as your demo file works on high resolution images. But for normal resolution images it works as equally as shared demo file. Can you please help me.

**Comment by Animatory** [comment]
If you want to run the model on high-resolution images, try these settings:
`Target size: 800, Expand ratio: 1.0`
